<div>acceleration:[:0.acceleration]</div>
<div>aero:[:0.aero]</div>
<div>braking:[:braking]</div>
<div>cornering:[:0.cornering]</div>
<div>handling:[:0.handling]</div>
<div>improvement:[:0.improvement]</div>
<div>level:[:0.level]</div>
<div>manufacturer_name:[:0.manufacturer_name]</div>
<div>manufacturer_picture:[:0.manufacturer_picture]</div>
<div>name:[:0.name]</div>
<div>nitrous:[:0.nitrous]</div>
<div>nos:[:0.nos]</div>
<div>parts_price:[:0.parts_price]</div>
<div>power:[:0.power]</div>
<div>ready:[:0.ready]</div>
<div>stopping:[:0.stopping]</div>
<div>top_speed:[:0.top_speed]</div>
<div>total_price:[:0.total_price]</div>
<div>traction:[:0.traction]</div>
<div>wear:[:0.wear]</div>
<div>weight:[:0.weight]</div>
<div>year:[:0.year]</div>